Repository wso2/carbon-identity-framework, pull requests merged in 2018-02, with the labels that each got.

#1331 Sync with 5.x.x branch
  components/application-mgt/org.wso2.carbon.identity.application.mgt/src/main/java/org/wso2/carbon/identity/application/mgt/ApplicationManagementServiceImpl.java
  components/authentication-framework/org.wso2.carbon.identity.application.authentication.framework/src/main/java/org/wso2/carbon/identity/application/authentication/framework/AbstractApplicationAuthenticator.java
  components/identity-core/org.wso2.carbon.identity.core/src/main/java/org/wso2/carbon/identity/core/IdentityClaimManager.java
  components/identity-core/org.wso2.carbon.identity.core/src/main/java/org/wso2/carbon/identity/core/bean/context/MessageContext.java
  components/identity-core/org.wso2.carbon.identity.core/src/main/java/org/wso2/carbon/identity/core/util/IdentityTenantUtil.java
  components/identity-mgt/org.wso2.carbon.identity.mgt.endpoint/src/main/java/org/wso2/carbon/identity/mgt/endpoint/client/api/NotificationApi.java
  components/identity-mgt/org.wso2.carbon.identity.mgt.endpoint/src/main/webapp/css/custom-common.css
  components/identity-mgt/org.wso2.carbon.identity.mgt.endpoint/src/main/webapp/password-recovery-confirm.jsp
  components/identity-mgt/org.wso2.carbon.identity.mgt.endpoint/src/main/webapp/password-recovery.jsp
  components/user-mgt/org.wso2.carbon.identity.user.registration/src/main/java/org/wso2/carbon/identity/user/registration/UserRegistrationService.java
Labels: 5.5.0

#1356 OAEP Fix configurable cipher transformations
  components/user-store/org.wso2.carbon.identity.user.store.configuration.deployer/pom.xml
  components/user-store/org.wso2.carbon.identity.user.store.configuration.deployer/src/main/java/org/wso2/carbon/identity/user/store/configuration/deployer/UserStoreConfigurationDeployer.java
  components/user-store/org.wso2.carbon.identity.user.store.configuration.deployer/src/main/java/org/wso2/carbon/identity/user/store/configuration/deployer/util/UserStoreUtil.java
  components/user-store/org.wso2.carbon.identity.user.store.configuration/pom.xml
  components/user-store/org.wso2.carbon.identity.user.store.configuration/src/main/java/org/wso2/carbon/identity/user/store/configuration/utils/SecondaryUserStoreConfigurationUtil.java
  pom.xml
Labels: kernel 4.4.x dep

#1357 Modify identity scripts
  features/identity-core/org.wso2.carbon.identity.core.server.feature/resources/dbscripts/db2.sql
  features/identity-core/org.wso2.carbon.identity.core.server.feature/resources/dbscripts/h2.sql
  features/identity-core/org.wso2.carbon.identity.core.server.feature/resources/dbscripts/mssql.sql
  features/identity-core/org.wso2.carbon.identity.core.server.feature/resources/dbscripts/mysql-5.7.sql
  features/identity-core/org.wso2.carbon.identity.core.server.feature/resources/dbscripts/mysql.sql
  features/identity-core/org.wso2.carbon.identity.core.server.feature/resources/dbscripts/oracle.sql
  features/identity-core/org.wso2.carbon.identity.core.server.feature/resources/dbscripts/oracle_rac.sql
  features/identity-core/org.wso2.carbon.identity.core.server.feature/resources/dbscripts/postgresql.sql
Labels: kernel 4.4.x dep

#1390 Fixed invalid format in default ACR javscript template in management console for conditional authentication
  components/application-mgt/org.wso2.carbon.identity.application.mgt.ui/src/main/resources/web/application/configure-authentication-flow.jsp
Labels: 5.5.0, Type/Bug
