Repository wso2/carbon-identity-framework, pull requests merged in 2020-01, with the labels that each got.

#2671 Fix inconstancy in the login and logout consent flows
  components/authentication-framework/org.wso2.carbon.identity.application.authentication.framework/src/main/java/org/wso2/carbon/identity/application/authentication/framework/handler/request/impl/consent/ConsentMgtPostAuthnHandler.java
  features/identity-core/org.wso2.carbon.identity.core.server.feature/resources/identity.xml
  features/identity-core/org.wso2.carbon.identity.core.server.feature/resources/identity.xml.j2
  features/identity-core/org.wso2.carbon.identity.core.server.feature/resources/org.wso2.carbon.identity.core.server.feature.default.json
Labels: Approval/Done, Code-Quality-Review/Done, Functionality-Review/Done

#2692 Addressing comments.
  components/identity-core/org.wso2.carbon.identity.core/src/main/java/org/wso2/carbon/identity/core/persistence/JDBCPersistenceManager.java
Labels: Approval/Done, Code-Quality-Review/Done, Functionality-Review/Done

#2701 Introduce a configuration to skip enforcing certificate expiry validation
  features/identity-core/org.wso2.carbon.identity.core.server.feature/resources/identity.xml.j2
  features/identity-core/org.wso2.carbon.identity.core.server.feature/resources/org.wso2.carbon.identity.core.server.feature.default.json
Labels: Approval/Done, Code-Quality-Review/Done, Functionality-Review/Done

#2705 Refactor state change with security policies
  components/security-mgt/org.wso2.carbon.security.mgt.ui/src/main/resources/web/securityconfig/index.jsp
  components/security-mgt/org.wso2.carbon.security.mgt.ui/src/main/resources/web/securityconfig/remove-security.jsp
Labels: Approval/Done, Code-Quality-Review/Done, Functionality-Review/Done

#2699 Fix NullPointerException
  components/functions-library-mgt/org.wso2.carbon.identity.functions.library.mgt/src/main/java/org/wso2/carbon/identity/functions/library/mgt/FunctionLibraryManagementAdminService.java
  components/functions-library-mgt/org.wso2.carbon.identity.functions.library.mgt/src/main/java/org/wso2/carbon/identity/functions/library/mgt/FunctionLibraryManagementServiceImpl.java
Labels: Approval/Done, Code-Quality-Review/Done, Functionality-Review/Done

#2708 Add idp basic information to getFederatedAssociationsOfUser method
  components/user-mgt/org.wso2.carbon.identity.user.profile/src/main/java/org/wso2/carbon/identity/user/profile/mgt/UserProfileAdmin.java
  components/user-mgt/org.wso2.carbon.identity.user.profile/src/main/java/org/wso2/carbon/identity/user/profile/mgt/association/federation/FederatedAssociationManagerImpl.java
  components/user-mgt/org.wso2.carbon.identity.user.profile/src/main/java/org/wso2/carbon/identity/user/profile/mgt/association/federation/model/AssociatedIdentityProvider.java
  components/user-mgt/org.wso2.carbon.identity.user.profile/src/main/java/org/wso2/carbon/identity/user/profile/mgt/association/federation/model/FederatedAssociation.java
Labels: Approval/Pending, Code-Quality-Review/Pending, Functionality-Review/Pending

#2710 [Fix] Claim mapping not deleted upon userstore deletion
  components/claim-mgt/org.wso2.carbon.identity.claim.metadata.mgt/pom.xml
  components/claim-mgt/org.wso2.carbon.identity.claim.metadata.mgt/src/main/java/org/wso2/carbon/identity/claim/metadata/mgt/ClaimMetadataManagementService.java
  components/claim-mgt/org.wso2.carbon.identity.claim.metadata.mgt/src/main/java/org/wso2/carbon/identity/claim/metadata/mgt/ClaimMetadataManagementServiceImpl.java
  components/claim-mgt/org.wso2.carbon.identity.claim.metadata.mgt/src/main/java/org/wso2/carbon/identity/claim/metadata/mgt/dao/CacheBackedLocalClaimDAO.java
  components/claim-mgt/org.wso2.carbon.identity.claim.metadata.mgt/src/main/java/org/wso2/carbon/identity/claim/metadata/mgt/dao/LocalClaimDAO.java
  components/claim-mgt/org.wso2.carbon.identity.claim.metadata.mgt/src/main/java/org/wso2/carbon/identity/claim/metadata/mgt/exception/ClaimMetadataException.java
  components/claim-mgt/org.wso2.carbon.identity.claim.metadata.mgt/src/main/java/org/wso2/carbon/identity/claim/metadata/mgt/exception/ClaimMetadataServerException.java
  components/claim-mgt/org.wso2.carbon.identity.claim.metadata.mgt/src/main/java/org/wso2/carbon/identity/claim/metadata/mgt/internal/IdentityClaimManagementServiceComponent.java
  components/claim-mgt/org.wso2.carbon.identity.claim.metadata.mgt/src/main/java/org/wso2/carbon/identity/claim/metadata/mgt/listener/ClaimConfigListener.java
  components/claim-mgt/org.wso2.carbon.identity.claim.metadata.mgt/src/main/java/org/wso2/carbon/identity/claim/metadata/mgt/util/ClaimConstants.java
  components/claim-mgt/org.wso2.carbon.identity.claim.metadata.mgt/src/main/java/org/wso2/carbon/identity/claim/metadata/mgt/util/SQLConstants.java
Labels: Approval/Pending, Code-Quality-Review/Pending, Functionality-Review/Pending

#2714 Continue IdentityUserIdResolverListener operation when the user list is empty
  components/identity-mgt/org.wso2.carbon.identity.mgt/src/main/java/org/wso2/carbon/identity/mgt/listener/IdentityUserIdResolverListener.java
Labels: Code-Quality-Review/Done, Functionality-Review/Done

#2585 Fix userStoreCountService for new backend implementation
  components/user-store/org.wso2.carbon.identity.user.store.count/src/main/java/org/wso2/carbon/identity/user/store/count/UserStoreCountService.java
  components/user-store/org.wso2.carbon.identity.user.store.count/src/main/java/org/wso2/carbon/identity/user/store/count/util/UserStoreCountUtils.java
Labels: Approval/Done, Code-Quality-Review/Done, Functionality-Review/Done, Internal-Contributor
