Repository wso2/carbon-identity-framework, pull requests merged in 2020-02, with the labels that each got.

#2731 Retrieve username without the userstore from user id
  components/identity-mgt/org.wso2.carbon.identity.mgt/src/main/java/org/wso2/carbon/identity/mgt/listener/IdentityUserNameResolverListener.java
Labels: Approval/Pending, Code-Quality-Review/Pending, Functionality-Review/Pending, Internal-Contributor

#2724 Improving cookie configurations
  features/identity-core/org.wso2.carbon.identity.core.server.feature/resources/identity.xml.j2
Labels: Approval/Pending, Code-Quality-Review/Pending, Functionality-Review/Pending

#2725 Fix application and internal role count from framework level
  components/user-store/org.wso2.carbon.identity.user.store.count/src/main/java/org/wso2/carbon/identity/user/store/count/UserStoreCountService.java
Labels: Approval/Done, Code-Quality-Review/Done, Functionality-Review/Done

#2733 [FIX] Encoding password regex
  components/user-mgt/org.wso2.carbon.user.mgt.ui/src/main/resources/web/user/add-step1.jsp
Labels: Approval/Done, Code-Quality-Review/Done, Functionality-Review/Done

#2735 Fix expired session data cleanup
  components/authentication-framework/org.wso2.carbon.identity.application.authentication.framework/src/main/java/org/wso2/carbon/identity/application/authentication/framework/store/SessionDataStore.java
Labels: Approval/Done, Code-Quality-Review/Done, Functionality-Review/Done

#2654 Add configurations for account verification on email address update.
  features/claim-mgt/org.wso2.carbon.claim.mgt.server.feature/resources/conf/claim-config.xml
  features/identity-core/org.wso2.carbon.identity.core.server.feature/resources/identity.xml.j2
  features/identity-core/org.wso2.carbon.identity.core.server.feature/resources/org.wso2.carbon.identity.core.server.feature.default.json
  features/identity-core/org.wso2.carbon.identity.core.server.feature/resources/org.wso2.carbon.identity.core.server.feature.unit-resolve.json
  features/identity-event/org.wso2.carbon.identity.event.server.feature/resources/identity-event.properties
  features/identity-event/org.wso2.carbon.identity.event.server.feature/resources/org.wso2.carbon.identity.event.server.feature.default.json
Labels: Approval/Done, Code-Quality-Review/Done, Functionality-Review/Done, Internal-Contributor

#2740 Add config for last login claim
  features/claim-mgt/org.wso2.carbon.claim.mgt.server.feature/resources/conf/claim-config.xml
  features/identity-core/org.wso2.carbon.identity.core.server.feature/resources/identity.xml
  features/identity-core/org.wso2.carbon.identity.core.server.feature/resources/identity.xml.j2
  features/identity-core/org.wso2.carbon.identity.core.server.feature/resources/org.wso2.carbon.identity.core.server.feature.default.json
Labels: Approval/Pending, Code-Quality-Review/Done, Functionality-Review/Pending

#2761 Fix possible null pointer error when updating the secondary user store from management console
  components/user-store/org.wso2.carbon.identity.user.store.configuration/src/main/java/org/wso2/carbon/identity/user/store/configuration/utils/SecondaryUserStoreConfigurationUtil.java
Labels: Code-Quality-Review/Pending, Functionality-Review/Done

#2713 Revert changes done in #2655
  components/authentication-framework/org.wso2.carbon.identity.application.authentication.framework/src/main/java/org/wso2/carbon/identity/application/authentication/framework/util/LoginContextManagementUtil.java
Labels: Approval/Done, Code-Quality-Review/Done, Functionality-Review/Done

#2753 Defining ajaxProcessor output to be text/plain
  components/entitlement/org.wso2.carbon.identity.entitlement.ui/src/main/resources/web/entitlement/prettyPrinter_ajaxprocessor.jsp
  components/policy-editor/org.wso2.carbon.policyeditor.ui/src/main/resources/web/policyeditor/prettyPrinter_ajaxprocessor.jsp
Labels: Approval/Pending, Code-Quality-Review/Pending, Functionality-Review/Pending

#2780 Encode html content in user management page of management console
  components/user-mgt/org.wso2.carbon.user.mgt.ui/src/main/resources/web/user/user-mgt.jsp
Labels: Code-Quality-Review/Done, Functionality-Review/Done, Internal-Contributor
